import Head from 'next/head'
import Header from '@/components/Header'
import Organize from '@/components/Organize'
import ToDoListSection from '@/components/ToDoListSection'
import GoodThings from '@/components/GoodThings'
import GetInTouch from '@/components/GetInTouch'
import Footer from '@/components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Coopers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Organize />
      <ToDoListSection />
      <GoodThings />
      <GetInTouch />
      <Footer />
    </>
  )
}
